Подкорректировал формат

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -208,6 +208,9 @@ services:
 
   kafka-0:
     image: bitnami/kafka:3.4
+    build:
+      context: .
+      dockerfile: Dockerfile.dev
     ports:
       - "9094:9094"
     environment:
@@ -228,6 +231,31 @@ services:
 
     volumes:
       - kafka_0_data:/bitnami/kafka
+    command: >
+      bash -c '
+        echo "Waiting for all controllers to be ready...";
+        brokers="kafka-0:9093 kafka-1:9093 kafka-2:9093";
+        for broker in $brokers; do
+            echo "Processing broker: $broker";
+            IFS=":" read -r host port <<< "$broker";
+            echo "Parsed host: $host, port: $port";
+            if [ -z "$host" ] || [ -z "$port" ]; then
+                echo "Error: Failed to parse host or port from broker string: $broker";
+                exit 1;
+            fi;
+            echo "Checking broker: $host:$port";
+            until nc -z -v -w5 "$host" "$port"; do
+                echo "Waiting for $host:$port to be available...";
+                sleep 5;
+            done;
+            echo "$broker is available";
+        done;
+        echo "All controllers are ready, starting Kafka...";
+        /opt/bitnami/kafka/bin/kafka-server-start.sh /opt/bitnami/kafka/config/server.properties
+      '
+    depends_on:
+    - kafka-1
+    - kafka-2
 
   kafka-1:
     image: bitnami/kafka:3.4
